long@hello:~$ kubectl get all -A -o wide
NAMESPACE             NAME                                                                  READY   STATUS      RESTARTS      AGE    IP               NODE    NOMINATED NODE   READINESS GATES
cattle-fleet-system   pod/fleet-agent-0                                                     2/2     Running     0             18h    10.32.0.5        vupc    <none>           <none>
cattle-system         pod/cattle-cluster-agent-7c95bb564b-9bmtv                             1/1     Running     0             18h    10.32.0.4        vupc    <none>           <none>
cattle-system         pod/cattle-cluster-agent-7c95bb564b-crpgv                             1/1     Running     1 (46m ago)   18h    10.32.0.3        vupc    <none>           <none>
default               pod/nvidia-plugin-test-2-57b7b7fcc7-ntbfq                             1/1     Running     0             23m    10.32.0.15       vupc    <none>           <none>
default               pod/nvidia-plugin-test-2-57b7b7fcc7-sjz29                             1/1     Running     0             23m    10.32.0.14       vupc    <none>           <none>
gpu-operator          pod/gpu-feature-discovery-vks77                                       2/2     Running     0             25m    10.32.0.12       vupc    <none>           <none>
gpu-operator          pod/gpu-operator-1730957745-node-feature-discovery-gc-84d48d5bs7l5d   1/1     Running     0             105m   10.32.0.6        vupc    <none>           <none>
gpu-operator          pod/gpu-operator-1730957745-node-feature-discovery-master-69c9xcnxl   1/1     Running     0             105m   10.36.0.3        hello   <none>           <none>
gpu-operator          pod/gpu-operator-1730957745-node-feature-discovery-worker-4x8jd       1/1     Running     0             105m   10.36.0.4        hello   <none>           <none>
gpu-operator          pod/gpu-operator-1730957745-node-feature-discovery-worker-dkrv4       1/1     Running     0             105m   10.32.0.7        vupc    <none>           <none>
gpu-operator          pod/gpu-operator-798db8c6f9-cl78c                                     1/1     Running     0             105m   10.36.0.5        hello   <none>           <none>
gpu-operator          pod/nvidia-container-toolkit-daemonset-828fs                          1/1     Running     0             104m   10.32.0.9        vupc    <none>           <none>
gpu-operator          pod/nvidia-cuda-validator-fvcxl                                       0/1     Completed   0             103m   10.32.0.13       vupc    <none>           <none>
gpu-operator          pod/nvidia-dcgm-exporter-fw2s8                                        1/1     Running     0             104m   10.32.0.11       vupc    <none>           <none>
gpu-operator          pod/nvidia-device-plugin-daemonset-9kqkg                              2/2     Running     0             25m    10.32.0.8        vupc    <none>           <none>
gpu-operator          pod/nvidia-operator-validator-hf2jj                                   1/1     Running     0             104m   10.32.0.10       vupc    <none>           <none>
kube-system           pod/coredns-5dd5756b68-cdrn2                                          1/1     Running     0             21h    10.36.0.2        hello   <none>           <none>
kube-system           pod/coredns-5dd5756b68-xrkjj                                          1/1     Running     0             21h    10.36.0.1        hello   <none>           <none>
kube-system           pod/etcd-hello                                                        1/1     Running     6             21h    10.208.164.167   hello   <none>           <none>
kube-system           pod/kube-apiserver-hello                                              1/1     Running     0             21h    10.208.164.167   hello   <none>           <none>
kube-system           pod/kube-controller-manager-hello                                     1/1     Running     0             21h    10.208.164.167   hello   <none>           <none>
kube-system           pod/kube-proxy-pr2sj                                                  1/1     Running     0             21h    10.208.164.167   hello   <none>           <none>
kube-system           pod/kube-proxy-r9s5g                                                  1/1     Running     0             21h    10.208.164.173   vupc    <none>           <none>
kube-system           pod/kube-scheduler-hello                                              1/1     Running     0             21h    10.208.164.167   hello   <none>           <none>
kube-system           pod/weave-net-mprwk                                                   2/2     Running     0             21h    10.208.164.167   hello   <none>           <none>
kube-system           pod/weave-net-r6lwg                                                   2/2     Running     0             21h    10.208.164.173   vupc    <none>           <none>
nginx-ingress         pod/nginx-ingress-controller-79d645f569-rl8c9                         1/1     Running     0             109m   10.32.0.2        vupc    <none>           <none>

NAMESPACE             NAME                               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE    SELECTOR
cattle-fleet-system   service/fleet-agent                ClusterIP   None             <none>        <none>                       18h    app=fleet-agent
cattle-system         service/cattle-cluster-agent       ClusterIP   10.111.13.78     <none>        80/TCP,443/TCP               18h    app=cattle-cluster-agent
default               service/kubernetes                 ClusterIP   10.96.0.1        <none>        443/TCP                      21h    <none>
gpu-operator          service/gpu-operator               ClusterIP   10.105.114.130   <none>        8080/TCP                     104m   app=gpu-operator
gpu-operator          service/nvidia-dcgm-exporter       ClusterIP   10.102.102.140   <none>        9400/TCP                     104m   app=nvidia-dcgm-exporter
kube-system           service/kube-dns                   ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP       21h    k8s-app=kube-dns
nginx-ingress         service/nginx-ingress-controller   NodePort    10.107.216.167   <none>        80:30080/TCP,443:30443/TCP   109m   app.kubernetes.io/instance=nginx-ingress,app.kubernetes.io/name=nginx-ingress

NAMESPACE      NAME                                                                   DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                                                          AGE    CONTAINERS                              IMAGES                                                                                        SELECTOR
gpu-operator   daemonset.apps/gpu-feature-discovery                                   1         1         1       1            1           nvidia.com/gpu.deploy.gpu-feature-discovery=true                       104m   gpu-feature-discovery,config-manager    nvcr.io/nvidia/k8s-device-plugin:v0.17.0-ubi9,nvcr.io/nvidia/k8s-device-plugin:v0.17.0-ubi9   app=gpu-feature-discovery,app.kubernetes.io/part-of=nvidia-gpu
gpu-operator   daemonset.apps/gpu-operator-1730957745-node-feature-discovery-worker   2         2         2       2            2           <none>                                                                 105m   worker                                  registry.k8s.io/nfd/node-feature-discovery:v0.16.6                                            app.kubernetes.io/instance=gpu-operator-1730957745,app.kubernetes.io/name=node-feature-discovery,role=worker
gpu-operator   daemonset.apps/nvidia-container-toolkit-daemonset                      1         1         1       1            1           nvidia.com/gpu.deploy.container-toolkit=true                           104m   nvidia-container-toolkit-ctr            nvcr.io/nvidia/k8s/container-toolkit:v1.17.0-ubuntu20.04                                      app=nvidia-container-toolkit-daemonset
gpu-operator   daemonset.apps/nvidia-dcgm-exporter                                    1         1         1       1            1           nvidia.com/gpu.deploy.dcgm-exporter=true                               104m   nvidia-dcgm-exporter                    nvcr.io/nvidia/k8s/dcgm-exporter:3.3.8-3.6.0-ubuntu22.04                                      app=nvidia-dcgm-exporter
gpu-operator   daemonset.apps/nvidia-device-plugin-daemonset                          1         1         1       1            1           nvidia.com/gpu.deploy.device-plugin=true                               104m   nvidia-device-plugin,config-manager     nvcr.io/nvidia/k8s-device-plugin:v0.17.0-ubi9,nvcr.io/nvidia/k8s-device-plugin:v0.17.0-ubi9   app=nvidia-device-plugin-daemonset
gpu-operator   daemonset.apps/nvidia-device-plugin-mps-control-daemon                 0         0         0       0            0           nvidia.com/gpu.deploy.device-plugin=true,nvidia.com/mps.capable=true   104m   mps-control-daemon-ctr,config-manager   nvcr.io/nvidia/k8s-device-plugin:v0.17.0-ubi9,nvcr.io/nvidia/k8s-device-plugin:v0.17.0-ubi9   app=nvidia-device-plugin-mps-control-daemon
gpu-operator   daemonset.apps/nvidia-driver-daemonset                                 0         0         0       0            0           nvidia.com/gpu.deploy.driver=true                                      104m   nvidia-driver-ctr                       nvcr.io/nvidia/driver:550.127.05-ubuntu24.04                                                  app=nvidia-driver-daemonset
gpu-operator   daemonset.apps/nvidia-mig-manager                                      0         0         0       0            0           nvidia.com/gpu.deploy.mig-manager=true                                 104m   nvidia-mig-manager                      nvcr.io/nvidia/cloud-native/k8s-mig-manager:v0.10.0-ubuntu20.04                               app=nvidia-mig-manager
gpu-operator   daemonset.apps/nvidia-operator-validator                               1         1         1       1            1           nvidia.com/gpu.deploy.operator-validator=true                          104m   nvidia-operator-validator               nvcr.io/nvidia/cloud-native/gpu-operator-validator:v24.9.0                                    app=nvidia-operator-validator,app.kubernetes.io/part-of=gpu-operator
kube-system    daemonset.apps/kube-proxy                                              2         2         2       2            2           kubernetes.io/os=linux                                                 21h    kube-proxy                              registry.k8s.io/kube-proxy:v1.28.15                                                           k8s-app=kube-proxy
kube-system    daemonset.apps/weave-net                                               2         2         2       2            2           <none>                                                                 21h    weave,weave-npc                         weaveworks/weave-kube:latest,weaveworks/weave-npc:latest                                      name=weave-net

NAMESPACE       NAME                                                                    READY   UP-TO-DATE   AVAILABLE   AGE    CONTAINERS         IMAGES                                                      SELECTOR
cattle-system   deployment.apps/cattle-cluster-agent                                    2/2     2            2           18h    cluster-register   rancher/rancher-agent:v2.9.3                                app=cattle-cluster-agent
default         deployment.apps/nvidia-plugin-test-2                                    2/2     2            2           23m    dcgmproftester11   nvidia/samples:dcgmproftester-2.0.10-cuda11.0-ubuntu18.04   app=nvidia-plugin-test-2
gpu-operator    deployment.apps/gpu-operator                                            1/1     1            1           105m   gpu-operator       nvcr.io/nvidia/gpu-operator:v24.9.0                         app=gpu-operator,app.kubernetes.io/component=gpu-operator
gpu-operator    deployment.apps/gpu-operator-1730957745-node-feature-discovery-gc       1/1     1            1           105m   gc                 registry.k8s.io/nfd/node-feature-discovery:v0.16.6          app.kubernetes.io/instance=gpu-operator-1730957745,app.kubernetes.io/name=node-feature-discovery,role=gc
gpu-operator    deployment.apps/gpu-operator-1730957745-node-feature-discovery-master   1/1     1            1           105m   master             registry.k8s.io/nfd/node-feature-discovery:v0.16.6          app.kubernetes.io/instance=gpu-operator-1730957745,app.kubernetes.io/name=node-feature-discovery,role=master
kube-system     deployment.apps/coredns                                                 2/2     2            2           21h    coredns            registry.k8s.io/coredns/coredns:v1.10.1                     k8s-app=kube-dns
nginx-ingress   deployment.apps/nginx-ingress-controller                                1/1     1            1           109m   nginx-ingress      nginx/nginx-ingress:3.7.1                                   app.kubernetes.io/instance=nginx-ingress,app.kubernetes.io/name=nginx-ingress

NAMESPACE       NAME                                                                               DESIRED   CURRENT   READY   AGE    CONTAINERS         IMAGES                                                      SELECTOR
cattle-system   replicaset.apps/cattle-cluster-agent-7c95bb564b                                    2         2         2       18h    cluster-register   rancher/rancher-agent:v2.9.3                                app=cattle-cluster-agent,pod-template-hash=7c95bb564b
default         replicaset.apps/nvidia-plugin-test-2-57b7b7fcc7                                    2         2         2       23m    dcgmproftester11   nvidia/samples:dcgmproftester-2.0.10-cuda11.0-ubuntu18.04   app=nvidia-plugin-test-2,pod-template-hash=57b7b7fcc7
gpu-operator    replicaset.apps/gpu-operator-1730957745-node-feature-discovery-gc-84d48d5b9f       1         1         1       105m   gc                 registry.k8s.io/nfd/node-feature-discovery:v0.16.6          app.kubernetes.io/instance=gpu-operator-1730957745,app.kubernetes.io/name=node-feature-discovery,pod-template-hash=84d48d5b9f,role=gc
gpu-operator    replicaset.apps/gpu-operator-1730957745-node-feature-discovery-master-69c9cc8db4   1         1         1       105m   master             registry.k8s.io/nfd/node-feature-discovery:v0.16.6          app.kubernetes.io/instance=gpu-operator-1730957745,app.kubernetes.io/name=node-feature-discovery,pod-template-hash=69c9cc8db4,role=master
gpu-operator    replicaset.apps/gpu-operator-798db8c6f9                                            1         1         1       105m   gpu-operator       nvcr.io/nvidia/gpu-operator:v24.9.0                         app=gpu-operator,app.kubernetes.io/component=gpu-operator,pod-template-hash=798db8c6f9
kube-system     replicaset.apps/coredns-5dd5756b68                                                 2         2         2       21h    coredns            registry.k8s.io/coredns/coredns:v1.10.1                     k8s-app=kube-dns,pod-template-hash=5dd5756b68
nginx-ingress   replicaset.apps/nginx-ingress-controller-79d645f569                                1         1         1       109m   nginx-ingress      nginx/nginx-ingress:3.7.1                                   app.kubernetes.io/instance=nginx-ingress,app.kubernetes.io/name=nginx-ingress,pod-template-hash=79d645f569

NAMESPACE             NAME                           READY   AGE   CONTAINERS                              IMAGES
cattle-fleet-system   statefulset.apps/fleet-agent   1/1     18h   fleet-agent,fleet-agent-clusterstatus   rancher/fleet-agent:v0.10.4,rancher/fleet-agent:v0.10.4
