apiVersion: v1
kind: Pod
metadata:
  name: go-demo-2  # tên pod 
  labels:
    type: stack
spec:
  containers:  # một pod này có 2 container(được nhưng không nên)
  - name: db   # trong trường hợp muốn gửi một lệnh cho container nào thì cần chỉ định chính xác 
    image: mongo:3.3
  # bectl exec -it -c db go-demo-2 ps aux
  - name: api
    image: vfarcic/go-demo-2
    env:
    - name: DB
      value: localhost
