apiVersion: v1
data:
  1060ti-6gb: |-
    version: v1
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: 6
kind: ConfigMap
metadata:
  creationTimestamp: '2024-11-07T06:54:13Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:1060ti-6gb: {}
      manager: agent
      operation: Update
      time: '2024-11-07T06:54:13Z'
  name: gpu-time-slicing-configmap
  namespace: gpu-operator
  resourceVersion: '147377'
  uid: bfb3d24b-6946-4613-beb7-6524369904a6
