apiVersion: v1
kind: Pod
metadata:
  name: test-1
spec:
  restartPolicy: OnFailure
  runtimeClassName: nvidia # k3s setitng requirement
  containers:
  - name: gpu-test
    image: nvcr.io/nvidia/pytorch:24.01-py3  # cai nay nagn vl
    command: [ "/bin/bash" ]
    args: [" -c 'cd /opt/pytorch/examples/upstream/mnist && python main.py'" ]
    resources:
      limits:
        nvidia.com/gpu: 1
  nodeSelector:
      nvidia.com/gpu.product : NVIDIA-A30-MIG-2g.12gb

---
apiVersion: v1
kind: Pod
metadata:
  name: test-2
spec:
  restartPolicy: OnFailure
  runtimeClassName: nvidia
  containers:
  - name: gpu-test
    image: nvcr.io/nvidia/pytorch:24.01-py3
    command: [ "/bin/bash" ]
    args: [" -c 'cd /opt/pytorch/examples/upstream/mnist && python main.py'" ]
    resources:
      limits:
        nvidia.com/gpu: 1
  nodeSelector:
      nvidia.com/gpu.product : NVIDIA-A30-MIG-2g.12gb