apiVersion: v1
kind: Pod
metadata:
  name: test-11
spec:
  restartPolicy: OnFailure
  runtimeClassName: nvidia
  containers:
  - name: gpu-test
    image: nvcr.io/nvidia/k8s/cuda-sample:nbody
    args: ["nbody", "-gpu", "-benchmark"]
    resources:
      limits:
        nvidia.com/gpu: 1
  nodeSelector:
      nvidia.com/gpu.product : NVIDIA-A30-MIG-2g.12gb

---
apiVersion: v1
kind: Pod
metadata:
  name: test-22
spec:
  restartPolicy: OnFailure
  runtimeClassName: nvidia
  containers:
  - name: gpu-test
    image: nvcr.io/nvidia/k8s/cuda-sample:nbody
    args: ["nbody", "-gpu", "-benchmark"]
    resources:
      limits:
        nvidia.com/gpu: 1
  nodeSelector:
      nvidia.com/gpu.product : NVIDIA-A30-MIG-2g.12gb
      # https://docs.k3s.io/advanced#alternative-container-runtime-support