VAGRANT_COMMAND = ARGV[0]

Vagrant.configure("2") do |config|

    if VAGRANT_COMMAND == "ssh"
      config.ssh.username = 'vagrant'
    end
    config.vm.box = "ubuntu/bionic64" # Chọn box bạn muốn sử dụng


    config.vm.provision "shell", inline: <<-SHELL
    if [ ! -f /vagrant/id_rsa ]; then
      ssh-keygen -t rsa -b 2048 -f /vagrant/id_rsa -q -N ""
    fi
    SHELL


##################################################################################################
    config.vm.define "machine1" do |machine1|
      machine1.vm.network "private_network", ip: "192.168.56.11"
      machine1.vm.hostname = "k8s-master1"
      machine1.vm.provider "virtualbox" do |vb|
            vb.memory = "2048" # 2GB RAM
            vb.cpus = 2       # 1 core CPU
          end  
      machine1.vm.provision "shell", inline: <<-SHELL
        adduser kubespray
        usermod -aG sudo kubespray
        echo kubespray ALL=NOPASSWD:ALL | sudo tee -a  /etc/sudoers.d/kubespray
        echo vagrant ALL=NOPASSWD:ALL | sudo tee -a  /etc/sudoers.d/vagrant
        swapoff -a
        sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
  
        mkdir -p /home/kubespray/.ssh
        sudo chown -R kubespray:kubespray /home/kubespray/.ssh
        sudo cat /vagrant/id_rsa.pub >> /home/kubespray/.ssh/authorized_keys
        sudo chmod 0600 /home/kubespray/.ssh/authorized_keys
        sudo cp /vagrant/id_rsa /home/kubespray/.ssh/id_rsa
        sudo chown -R kubespray:kubespray /home/kubespray/.ssh


# Ghi nội dung sau ra file /etc/hosts để truy cập được các máy theo HOSTNAME
cat >>/etc/hosts<<EOF
192.168.56.11 k8s-master1
192.168.56.12 k8s-master2
192.168.56.12 k8s-master3
192.168.56.21 k8s-node1
192.168.56.22 k8s-node2
192.168.56.23 k8s-node3
192.168.56.10 k8s-kubespray
EOF
  
        # Cài đặt múi giờ
        sudo timedatectl set-timezone Asia/Ho_Chi_Minh
        # Cấu hình proxy trong /etc/environment
        echo 'http_proxy="http://10.60.117.103:8085/"' | sudo tee -a /etc/environment
        echo 'https_proxy="http://10.60.117.103:8085/"' | sudo tee -a /etc/environment
        echo 'no_proxy="localhost,127.0.0.1"' | sudo tee -a /etc/environment
        # Cấu hình proxy cho apt và apt-get
        echo 'Acquire::http::Proxy "http://10.60.117.103:8085/";' | sudo tee /etc/apt/apt.conf.d/95proxies
        echo 'Acquire::https::Proxy "http://10.60.117.103:8085/";' | sudo tee -a /etc/apt/apt.conf.d/95proxies
        
        SHELL
      end

      
##################################################################################################################
config.vm.define "machine2" do |machine2|
  machine2.vm.network "private_network", ip: "192.168.56.12"
  machine2.vm.hostname = "k8s-master2"
  machine2.vm.provider "virtualbox" do |vb|
        vb.memory = "2048" # 2GB RAM
        vb.cpus = 2       # 1 core CPU
      end  
  machine2.vm.provision "shell", inline: <<-SHELL
    adduser kubespray
    usermod -aG sudo kubespray
    echo kubespray ALL=NOPASSWD:ALL | sudo tee -a  /etc/sudoers.d/kubespray
    echo vagrant ALL=NOPASSWD:ALL | sudo tee -a  /etc/sudoers.d/vagrant
    swapoff -a
    sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    mkdir -p /home/kubespray/.ssh
    sudo chown -R kubespray:kubespray /home/kubespray/.ssh
    sudo cat /vagrant/id_rsa.pub >> /home/kubespray/.ssh/authorized_keys
    sudo chmod 0600 /home/kubespray/.ssh/authorized_keys
    sudo cp /vagrant/id_rsa /home/kubespray/.ssh/id_rsa
    sudo chown -R kubespray:kubespray /home/kubespray/.ssh


# Ghi nội dung sau ra file /etc/hosts để truy cập được các máy theo HOSTNAME
cat >>/etc/hosts<<EOF
192.168.56.11 k8s-master1
192.168.56.12 k8s-master2
192.168.56.12 k8s-master3
192.168.56.21 k8s-node1
192.168.56.22 k8s-node2
192.168.56.23 k8s-node3
192.168.56.10 k8s-kubespray
EOF

    # Cài đặt múi giờ
    sudo timedatectl set-timezone Asia/Ho_Chi_Minh
    # Cấu hình proxy trong /etc/environment
    echo 'http_proxy="http://10.60.117.103:8085/"' | sudo tee -a /etc/environment
    echo 'https_proxy="http://10.60.117.103:8085/"' | sudo tee -a /etc/environment
    echo 'no_proxy="localhost,127.0.0.1"' | sudo tee -a /etc/environment
    # Cấu hình proxy cho apt và apt-get
    echo 'Acquire::http::Proxy "http://10.60.117.103:8085/";' | sudo tee /etc/apt/apt.conf.d/95proxies
    echo 'Acquire::https::Proxy "http://10.60.117.103:8085/";' | sudo tee -a /etc/apt/apt.conf.d/95proxies
    
    SHELL
  end

##################################################################################################################
    config.vm.define "machine3" do |machine3|
      machine3.vm.network "private_network", ip: "192.168.56.13"
      machine3.vm.hostname = "k8s-master3"
      machine3.vm.provider "virtualbox" do |vb|
            vb.memory = "2048" # 2GB RAM
            vb.cpus = 2       # 1 core CPU
          end  
      machine3.vm.provision "shell", inline: <<-SHELL
        adduser kubespray
        usermod -aG sudo kubespray
        echo kubespray ALL=NOPASSWD:ALL | sudo tee -a  /etc/sudoers.d/kubespray
        echo vagrant ALL=NOPASSWD:ALL | sudo tee -a  /etc/sudoers.d/vagrant
        swapoff -a
        sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
  
        mkdir -p /home/kubespray/.ssh
        sudo chown -R kubespray:kubespray /home/kubespray/.ssh
        sudo cat /vagrant/id_rsa.pub >> /home/kubespray/.ssh/authorized_keys
        sudo chmod 0600 /home/kubespray/.ssh/authorized_keys
        sudo cp /vagrant/id_rsa /home/kubespray/.ssh/id_rsa
        sudo chown -R kubespray:kubespray /home/kubespray/.ssh


# Ghi nội dung sau ra file /etc/hosts để truy cập được các máy theo HOSTNAME
cat >>/etc/hosts<<EOF
192.168.56.11 k8s-master1
192.168.56.12 k8s-master2
192.168.56.12 k8s-master3
192.168.56.21 k8s-node1
192.168.56.22 k8s-node2
192.168.56.23 k8s-node3
192.168.56.10 k8s-kubespray
EOF
  
        # Cài đặt múi giờ
        sudo timedatectl set-timezone Asia/Ho_Chi_Minh
        # Cấu hình proxy trong /etc/environment
        echo 'http_proxy="http://10.60.117.103:8085/"' | sudo tee -a /etc/environment
        echo 'https_proxy="http://10.60.117.103:8085/"' | sudo tee -a /etc/environment
        echo 'no_proxy="localhost,127.0.0.1"' | sudo tee -a /etc/environment
        # Cấu hình proxy cho apt và apt-get
        echo 'Acquire::http::Proxy "http://10.60.117.103:8085/";' | sudo tee /etc/apt/apt.conf.d/95proxies
        echo 'Acquire::https::Proxy "http://10.60.117.103:8085/";' | sudo tee -a /etc/apt/apt.conf.d/95proxies
        
        SHELL
      end
  
##################################################################################################################
    config.vm.define "machine4" do |machine4|
      machine4.vm.network "private_network", ip: "192.168.56.21"
      machine4.vm.hostname = "k8s-node1"
      machine4.vm.provider "virtualbox" do |vb|
            vb.memory = "1024" # 2GB RAM
            vb.cpus = 2       # 1 core CPU
          end  
      machine4.vm.provision "shell", inline: <<-SHELL
        adduser kubespray
        usermod -aG sudo kubespray
        echo kubespray ALL=NOPASSWD:ALL | sudo tee -a  /etc/sudoers.d/kubespray
        echo vagrant ALL=NOPASSWD:ALL | sudo tee -a  /etc/sudoers.d/vagrant
        swapoff -a
        sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
  
        mkdir -p /home/kubespray/.ssh
        sudo chown -R kubespray:kubespray /home/kubespray/.ssh
        sudo cat /vagrant/id_rsa.pub >> /home/kubespray/.ssh/authorized_keys
        sudo chmod 0600 /home/kubespray/.ssh/authorized_keys
        sudo cp /vagrant/id_rsa /home/kubespray/.ssh/id_rsa
        sudo chown -R kubespray:kubespray /home/kubespray/.ssh


# Ghi nội dung sau ra file /etc/hosts để truy cập được các máy theo HOSTNAME
cat >>/etc/hosts<<EOF
192.168.56.11 k8s-master1
192.168.56.12 k8s-master2
192.168.56.12 k8s-master3
192.168.56.21 k8s-node1
192.168.56.22 k8s-node2
192.168.56.23 k8s-node3
192.168.56.10 k8s-kubespray
EOF
  
        # Cài đặt múi giờ
        sudo timedatectl set-timezone Asia/Ho_Chi_Minh
        # Cấu hình proxy trong /etc/environment
        echo 'http_proxy="http://10.60.117.103:8085/"' | sudo tee -a /etc/environment
        echo 'https_proxy="http://10.60.117.103:8085/"' | sudo tee -a /etc/environment
        echo 'no_proxy="localhost,127.0.0.1"' | sudo tee -a /etc/environment
        # Cấu hình proxy cho apt và apt-get
        echo 'Acquire::http::Proxy "http://10.60.117.103:8085/";' | sudo tee /etc/apt/apt.conf.d/95proxies
        echo 'Acquire::https::Proxy "http://10.60.117.103:8085/";' | sudo tee -a /etc/apt/apt.conf.d/95proxies
        
        SHELL
      end
  
##################################################################################################################
config.vm.define "machine5" do |machine5|
  machine5.vm.network "private_network", ip: "192.168.56.22"
  machine5.vm.hostname = "k8s-node2"
  machine5.vm.provider "virtualbox" do |vb|
        vb.memory = "1024" # 2GB RAM
        vb.cpus = 2       # 1 core CPU
      end  
  machine5.vm.provision "shell", inline: <<-SHELL
    adduser kubespray
    usermod -aG sudo kubespray
    echo kubespray ALL=NOPASSWD:ALL | sudo tee -a  /etc/sudoers.d/kubespray
    echo vagrant ALL=NOPASSWD:ALL | sudo tee -a  /etc/sudoers.d/vagrant
    swapoff -a
    sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    mkdir -p /home/kubespray/.ssh
    sudo chown -R kubespray:kubespray /home/kubespray/.ssh
    sudo cat /vagrant/id_rsa.pub >> /home/kubespray/.ssh/authorized_keys
    sudo chmod 0600 /home/kubespray/.ssh/authorized_keys
    sudo cp /vagrant/id_rsa /home/kubespray/.ssh/id_rsa
    sudo chown -R kubespray:kubespray /home/kubespray/.ssh


# Ghi nội dung sau ra file /etc/hosts để truy cập được các máy theo HOSTNAME
cat >>/etc/hosts<<EOF
192.168.56.11 k8s-master1
192.168.56.12 k8s-master2
192.168.56.12 k8s-master3
192.168.56.21 k8s-node1
192.168.56.22 k8s-node2
192.168.56.23 k8s-node3
192.168.56.10 k8s-kubespray
EOF

    # Cài đặt múi giờ
    sudo timedatectl set-timezone Asia/Ho_Chi_Minh
    # Cấu hình proxy trong /etc/environment
    echo 'http_proxy="http://10.60.117.103:8085/"' | sudo tee -a /etc/environment
    echo 'https_proxy="http://10.60.117.103:8085/"' | sudo tee -a /etc/environment
    echo 'no_proxy="localhost,127.0.0.1"' | sudo tee -a /etc/environment
    # Cấu hình proxy cho apt và apt-get
    echo 'Acquire::http::Proxy "http://10.60.117.103:8085/";' | sudo tee /etc/apt/apt.conf.d/95proxies
    echo 'Acquire::https::Proxy "http://10.60.117.103:8085/";' | sudo tee -a /etc/apt/apt.conf.d/95proxies
    
    SHELL
  end

##################################################################################################################
config.vm.define "machine6" do |machine6|
  machine6.vm.network "private_network", ip: "192.168.56.23"
  machine6.vm.hostname = "k8s-node3"
  machine6.vm.provider "virtualbox" do |vb|
        vb.memory = "1024" # 2GB RAM
        vb.cpus = 2       # 1 core CPU
      end  
  machine6.vm.provision "shell", inline: <<-SHELL
    adduser kubespray
    usermod -aG sudo kubespray
    echo kubespray ALL=NOPASSWD:ALL | sudo tee -a  /etc/sudoers.d/kubespray
    echo vagrant ALL=NOPASSWD:ALL | sudo tee -a  /etc/sudoers.d/vagrant
    swapoff -a
    sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    mkdir -p /home/kubespray/.ssh
    sudo chown -R kubespray:kubespray /home/kubespray/.ssh
    sudo cat /vagrant/id_rsa.pub >> /home/kubespray/.ssh/authorized_keys
    sudo chmod 0600 /home/kubespray/.ssh/authorized_keys
    sudo cp /vagrant/id_rsa /home/kubespray/.ssh/id_rsa
    sudo chown -R kubespray:kubespray /home/kubespray/.ssh


# Ghi nội dung sau ra file /etc/hosts để truy cập được các máy theo HOSTNAME
cat >>/etc/hosts<<EOF
192.168.56.11 k8s-master1
192.168.56.12 k8s-master2
192.168.56.12 k8s-master3
192.168.56.21 k8s-node1
192.168.56.22 k8s-node2
192.168.56.23 k8s-node3
192.168.56.10 k8s-kubespray
EOF

    # Cài đặt múi giờ
    sudo timedatectl set-timezone Asia/Ho_Chi_Minh
    # Cấu hình proxy trong /etc/environment
    echo 'http_proxy="http://10.60.117.103:8085/"' | sudo tee -a /etc/environment
    echo 'https_proxy="http://10.60.117.103:8085/"' | sudo tee -a /etc/environment
    echo 'no_proxy="localhost,127.0.0.1"' | sudo tee -a /etc/environment
    # Cấu hình proxy cho apt và apt-get
    echo 'Acquire::http::Proxy "http://10.60.117.103:8085/";' | sudo tee /etc/apt/apt.conf.d/95proxies
    echo 'Acquire::https::Proxy "http://10.60.117.103:8085/";' | sudo tee -a /etc/apt/apt.conf.d/95proxies
    
    SHELL
  end

##################################################################################################################
config.vm.define "machine7" do |machine7|
  machine7.vm.network "private_network", ip: "192.168.56.10"
  machine7.vm.hostname = "k8s-kubespray"
  machine7.vm.provider "virtualbox" do |vb|
        vb.memory = "2000" # 2GB RAM
        vb.cpus = 2       # 1 core CPU
      end  
  machine7.vm.provision "shell", inline: <<-SHELL
    adduser kubespray
    usermod -aG sudo kubespray
    echo kubespray ALL=NOPASSWD:ALL | sudo tee -a  /etc/sudoers.d/kubespray
    echo vagrant ALL=NOPASSWD:ALL | sudo tee -a  /etc/sudoers.d/vagrant
    swapoff -a
    sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    mkdir -p /home/kubespray/.ssh
    sudo chown -R kubespray:kubespray /home/kubespray/.ssh
    sudo cat /vagrant/id_rsa.pub >> /home/kubespray/.ssh/authorized_keys
    sudo chmod 0600 /home/kubespray/.ssh/authorized_keys
    sudo cp /vagrant/id_rsa /home/kubespray/.ssh/id_rsa
    sudo chown -R kubespray:kubespray /home/kubespray/.ssh


# Ghi nội dung sau ra file /etc/hosts để truy cập được các máy theo HOSTNAME
cat >>/etc/hosts<<EOF
192.168.56.11 k8s-master1
192.168.56.12 k8s-master2
192.168.56.12 k8s-master3
192.168.56.21 k8s-node1
192.168.56.22 k8s-node2
192.168.56.23 k8s-node3
192.168.56.10 k8s-kubespray
EOF

    # Cài đặt múi giờ
    sudo timedatectl set-timezone Asia/Ho_Chi_Minh
    # Cấu hình proxy trong /etc/environment
    echo 'http_proxy="http://10.60.117.103:8085/"' | sudo tee -a /etc/environment
    echo 'https_proxy="http://10.60.117.103:8085/"' | sudo tee -a /etc/environment
    echo 'no_proxy="localhost,127.0.0.1"' | sudo tee -a /etc/environment
    # Cấu hình proxy cho apt và apt-get
    echo 'Acquire::http::Proxy "http://10.60.117.103:8085/";' | sudo tee /etc/apt/apt.conf.d/95proxies
    echo 'Acquire::https::Proxy "http://10.60.117.103:8085/";' | sudo tee -a /etc/apt/apt.conf.d/95proxies

#     cd /root && git clone https://github.com/kubernetes-sigs/kubespray.git  && cd kubespray/ && git checkout release-2.21 && cp -rf inventory/sample inventory/long-cluster && rm inventory/long-cluster/inventory.ini

#     cat >>/root/kubespray/inventory/long-cluster/inventory.ini<<EOF
# [all]
# k8s-master1  ansible_host=192.168.56.11    ip=192.168.56.11
# k8s-master2  ansible_host=192.168.56.12    ip=192.168.56.12
# k8s-master3  ansible_host=192.168.56.13    ip=192.168.56.13
# k8s-node1  ansible_host=192.168.56.21     ip=192.168.56.21
# k8s-node2  ansible_host=192.168.56.22     ip=192.168.56.22
# k8s-node3  ansible_host=192.168.56.23     ip=192.168.56.23

# [kube_control_plane]
# k8s-master1
# k8s-master2
# k8s-master3

# [kube_node]
# k8s-node1
# k8s-node2
# k8s-node3

# [etcd]
# k8s-master1
# k8s-master2
# k8s-master3

# [k8s_cluster:children]
# kube_node
# kube_control_plane

# [calico_rr]

# [vault]
# k8s-master1
# k8s-master2
# k8s-master3
# k8s-node1
# k8s-node2
# k8s-node3
# EOF

#     apt-get update && sudo apt update
#     apt-get install -y docker.io
#     mkdir -p /etc/systemd/system/docker.service.d/

#     cat >>/etc/systemd/system/docker.service.d/http-proxy.conf <<EOF
# [Service]
# Environment="HTTP_PROXY=http://10.60.117.103:8085/"
# Environment="HTTPS_PROXY=http://10.60.117.103:8085/"

# EOF 
#     systemctl daemon-reload
#     systemctl restart docker

    # sudo docker run --rm -it \
    #   --mount type=bind,source=/root/kubespray/inventory/long-cluster,dst=/inventory \
    #   --mount type=bind,source=/home/kubespray/.ssh/id_rsa,dst=/root/.ssh/id_rsa \
    #   quay.io/kubespray/kubespray:v2.21.0 \
    #   bash -c "export ANSIBLE_HOST_KEY_CHECKING=False  && ansible-playbook -i /inventory/inventory.ini cluster.yml --user=kubespray --become"
    SHELL
  end

##################################################################################################################
end
