VAGRANT_COMMAND = ARGV[0]

Vagrant.configure("2") do |config|

    if VAGRANT_COMMAND == "ssh"
      config.ssh.username = 'vagrant'
    end
    config.vm.box = "ubuntu/bionic64" # Chọn box bạn muốn sử dụng

    # Khởi tạo máy ảo thứ nhất
    config.vm.define "machine1" do |machine1|
    machine1.vm.network "private_network", ip: "192.168.56.11"
    config.vm.hostname = "k8s-master1"
    machine1.vm.provider "virtualbox" do |vb|
          vb.memory = "1500" # 2GB RAM
          vb.cpus = 2       # 1 core CPU
        end
    config.vm.provision "file", source: "./ssh_config", destination: "/home/vagrant/.ssh/config"

    machine1.vm.provision "shell", inline: <<-SHELL
        adduser spray
        usermod -aG sudo spray
        echo spray ALL=NOPASSWD:ALL | sudo tee -a  /etc/sudoers.d/spray
        echo vagrant ALL=NOPASSWD:ALL | sudo tee -a  /etc/sudoers.d/vagrant
        # useradd k8scontrol
        # echo "123" | passwd --stdin k8scontrol
        # usermod -aG wheel k8scontrol
        # sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        # cp /home/vagrant/.ssh/config
        # systemctl reload sshd
        swapoff -a
        sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

        mkdir -p /home/spray/.ssh/config

cat >>/home/spray/.ssh/config/ssh_config<<EOF
Host localhost
  StrictHostKeyChecking no

Host 0.0.0.0
  StrictHostKeyChecking no
  
Host k8s-*
   StrictHostKeyChecking no
   UserKnownHostsFile=/dev/null
EOF

        chown -R spray:spray /home/spray/.ssh
        chmod 700 /home/spray/.ssh
        chmod 600 /home/spray/.ssh/config/ssh_config
        systemctl reload sshd


# Ghi nội dung sau ra file /etc/hosts để truy cập được các máy theo HOSTNAME
cat >>/etc/hosts<<EOF
192.168.56.11 k8s-master1
192.168.56.12 k8s-master2
192.168.56.10 k8s-kubespray
EOF

        # Cài đặt múi giờ
        sudo timedatectl set-timezone Asia/Ho_Chi_Minh
        # Cấu hình proxy trong /etc/environment
        echo 'http_proxy="http://10.60.117.103:8085/"' | sudo tee -a /etc/environment
        echo 'https_proxy="http://10.60.117.103:8085/"' | sudo tee -a /etc/environment
        echo 'no_proxy="localhost,127.0.0.1"' | sudo tee -a /etc/environment
        # Cấu hình proxy cho wget
        echo 'use_proxy = on' | sudo tee -a /etc/wgetrc
        echo 'http_proxy = http://10.60.117.103:8085/' | sudo tee -a /etc/wgetrc
        echo 'https_proxy = http://10.60.117.103:8085/' | sudo tee -a /etc/wgetrc
        # Cấu hình proxy cho apt và apt-get
        echo 'Acquire::http::Proxy "http://10.60.117.103:8085/";' | sudo tee /etc/apt/apt.conf.d/95proxies
        echo 'Acquire::https::Proxy "http://10.60.117.103:8085/";' | sudo tee -a /etc/apt/apt.conf.d/95proxies
        
        SHELL
    end

##################################################################################################################

    # Khởi tạo máy ảo thứ nhất
    config.vm.define "machine2" do |machine2|
      machine2.vm.network "private_network", ip: "192.168.56.12"
      config.vm.hostname = "k8s-master2"
      machine2.vm.provider "virtualbox" do |vb|
            vb.memory = "1500" # 2GB RAM
            vb.cpus = 2       # 1 core CPU
          end
      config.vm.provision "file", source: "./ssh_config", destination: "/home/vagrant/.ssh/config"
  
      machine2.vm.provision "shell", inline: <<-SHELL
          adduser spray
          usermod -aG sudo spray
          echo spray ALL=NOPASSWD:ALL | sudo tee -a  /etc/sudoers.d/spray
          echo vagrant ALL=NOPASSWD:ALL | sudo tee -a  /etc/sudoers.d/vagrant
          # useradd k8scontrol
          # echo "123" | passwd --stdin k8scontrol
          # usermod -aG wheel k8scontrol
          # sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
          # cp /home/vagrant/.ssh/config
          # systemctl reload sshd
          swapoff -a
          sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
  
          mkdir -p /home/spray/.ssh/config
  
cat >>/home/spray/.ssh/config/ssh_config<<EOF
Host localhost
  StrictHostKeyChecking no

Host 0.0.0.0
  StrictHostKeyChecking no
  
Host k8s-*
    StrictHostKeyChecking no
    UserKnownHostsFile=/dev/null
EOF

        chown -R spray:spray /home/spray/.ssh
        chmod 700 /home/spray/.ssh
        chmod 600 /home/spray/.ssh/config/ssh_config
        systemctl reload sshd


# Ghi nội dung sau ra file /etc/hosts để truy cập được các máy theo HOSTNAME
cat >>/etc/hosts<<EOF
192.168.56.11 k8s-master1
192.168.56.12 k8s-master2
192.168.56.10 k8s-kubespray
EOF
  
          # Cài đặt múi giờ
          sudo timedatectl set-timezone Asia/Ho_Chi_Minh
          # Cấu hình proxy trong /etc/environment
          echo 'http_proxy="http://10.60.117.103:8085/"' | sudo tee -a /etc/environment
          echo 'https_proxy="http://10.60.117.103:8085/"' | sudo tee -a /etc/environment
          echo 'no_proxy="localhost,127.0.0.1"' | sudo tee -a /etc/environment
          # Cấu hình proxy cho wget
          echo 'use_proxy = on' | sudo tee -a /etc/wgetrc
          echo 'http_proxy = http://10.60.117.103:8085/' | sudo tee -a /etc/wgetrc
          echo 'https_proxy = http://10.60.117.103:8085/' | sudo tee -a /etc/wgetrc
          # Cấu hình proxy cho apt và apt-get
          echo 'Acquire::http::Proxy "http://10.60.117.103:8085/";' | sudo tee /etc/apt/apt.conf.d/95proxies
          echo 'Acquire::https::Proxy "http://10.60.117.103:8085/";' | sudo tee -a /etc/apt/apt.conf.d/95proxies
          
          SHELL
      end
  
##################################################################################################################
end